In [1]:
import pandas as pd

df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
df.columns
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
data = {
    "PassengerId": range(1, 16),

    "Survived": [1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
                 0, 1, 0, 1, 1],

    "Pclass": [1, 3, 2, 3, 1, 3, 2, 1, 3, 2,
               3, 1, 3, 2, 1],

    "Sex": ["female", "male", "female", "male", "female", "male", "female", "male",
            "male", "female", "male", "female", "male", "female", "female"],

    "Age": [22, 35, 26, 40, 28, 30, 19, 45, 50, 23,
            33, 27, 41, 29, 21]
}
df_custom = pd.DataFrame(data, index=[f"P{i}" for i in range(1, 16)])
df_custom

     PassengerId  Survived  Pclass     Sex  Age
P1             1         1       1  female   22
P2             2         0       3    male   35
P3             3         1       2  female   26
P4             4         0       3    male   40
P5             5         1       1  female   28
P6             6         0       3    male   30
P7             7         1       2  female   19
P8             8         1       1    male   45
P9             9         0       3    male   50
P10           10         1       2  female   23
P11           11         0       3    male   33
P12           12         1       1  female   27
P13           13         0       3    male   41
P14           14         1       2  female   29
P15           15         1       1  female   21

In [3]:
df_custom.describe()

       PassengerId   Survived     Pclass        Age
count    15.000000  15.000000  15.000000  15.000000
mean      8.000000   0.600000   2.066667  31.266667
std       4.472136   0.507093   0.883715   9.261801
min       1.000000   0.000000   1.000000  19.000000
25%       4.500000   0.000000   1.000000  24.500000
50%       8.000000   1.000000   2.000000  29.000000
75%      11.500000   1.000000   3.000000  37.500000
max      15.000000   1.000000   3.000000  50.000000

In [4]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [5]:
df.columns
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

if "Age" in df.columns:
    df["Age"] = df["Age"].fillna(df["Age"].median())


if "Embarked" in df.columns:
    df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])


if "Cabin" in df.columns:
    df = df.drop("Cabin", axis=1)
    df.columns = df.columns.str.strip()


df = df.drop_duplicates()
for col in df.columns:
    print(col)

PassengerId
Survived
Pclass
Name
Sex
Age
SibSp
Parch
Ticket
Fare
Embarked

In [6]:
df.groupby("Sex")["Survived"].mean()

df.groupby("Pclass")["Survived"].mean()

df.groupby("Pclass")["Age"].mean()

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

In [7]:
df["AgeGroup"] = pd.cut(df["Age"],
                       bins=[0, 12, 18, 60, 100],
                       labels=["Child", "Teen", "Adult", "Senior"])

df.groupby("AgeGroup", observed=True)["Survived"].mean()

AgeGroup
Child     0.579710
Teen      0.428571
Adult     0.365753
Senior    0.227273
Name: Survived, dtype: float64

In [8]:
df[(df["Sex"] == "female") & (df["Survived"] == 1)]

df[(df["Age"] < 12) & (df["Survived"] == 1)]

df[(df["Pclass"] == 1) & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,AgeGroup
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,Adult
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Adult
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S,Adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,28.0,1,0,PC 17569,146.5208,C,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S,Adult
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,S,Adult
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,Adult